package production

import "errors"

var (
	ErrDuplicateProductionDefinition = errors.New("duplicate production definition")
	ErrDuplicateBuildingDefinition   = errors.New("duplicate building production definition")
	ErrUnknownProductionDefinition   = errors.New("unknown production definition")
	ErrProductionSourceMismatch      = errors.New("production source definition mismatch")
	ErrUnknownBuildingDefinition     = errors.New("unknown planet building definition")
	ErrBuildingSourceMismatch        = errors.New("planet building source mismatch")
	ErrInvalidBuildingID             = errors.New("invalid planet building id")
	ErrInvalidBuildingCategory       = errors.New("invalid building category")
	ErrInvalidBuildingType           = errors.New("invalid building type")
	ErrInvalidBuildingLevel          = errors.New("invalid building level")
	ErrInvalidBuildingState          = errors.New("invalid building state")
	ErrInvalidBuildingRate           = errors.New("invalid planet building rate")
	ErrEmptyProductionOutputs        = errors.New("empty production outputs")
	ErrEmptyRefineryInputs           = errors.New("empty refinery inputs")
	ErrUnexpectedExtractorInputs     = errors.New("unexpected extractor inputs")
	ErrDuplicateProductionInput      = errors.New("duplicate production input")
	ErrDuplicateProductionOutput     = errors.New("duplicate production output")
	ErrDuplicateBuildingInput        = errors.New("duplicate planet building input")
	ErrDuplicateBuildingOutput       = errors.New("duplicate planet building output")
	ErrEmptyBuildingOutput           = errors.New("empty planet building output")
	ErrInvalidProductionRate         = errors.New("invalid production rate per hour")
	ErrInvalidEnergyCost             = errors.New("invalid energy cost per hour")
	ErrInvalidEnergyRate             = errors.New("invalid planet energy rate")
	ErrInvalidStorageCapacity        = errors.New("invalid planet storage capacity")
	ErrStorageOverCapacity           = errors.New("planet storage over capacity")
	ErrDuplicateStorageItem          = errors.New("duplicate planet storage item")
	ErrUnknownStorageItem            = errors.New("unknown planet storage item")
	ErrZeroProductionTimestamp       = errors.New("zero planet production timestamp")
	ErrInvalidProductionState        = errors.New("invalid planet production state")
	ErrProductionSnapshotIncomplete  = errors.New("incomplete planet production snapshot")
	ErrInvalidProductionEvent        = errors.New("invalid planet production event")
)

var ErrInvalidClaimProductionInitializerConfig = errors.New("invalid claim production initializer config")
