package production

import "errors"

var (
	ErrDuplicateProductionDefinition     = errors.New("duplicate production definition")
	ErrDuplicateBuildingDefinition       = errors.New("duplicate building production definition")
	ErrUnknownProductionDefinition       = errors.New("unknown production definition")
	ErrProductionSourceMismatch          = errors.New("production source definition mismatch")
	ErrUnknownBuildingDefinition         = errors.New("unknown planet building definition")
	ErrBuildingSourceMismatch            = errors.New("planet building source mismatch")
	ErrInvalidBuildingID                 = errors.New("invalid planet building id")
	ErrInvalidBuildingCategory           = errors.New("invalid building category")
	ErrInvalidBuildingType               = errors.New("invalid building type")
	ErrInvalidBuildingLevel              = errors.New("invalid building level")
	ErrInvalidBuildingState              = errors.New("invalid building state")
	ErrInvalidBuildingRate               = errors.New("invalid planet building rate")
	ErrEmptyProductionOutputs            = errors.New("empty production outputs")
	ErrEmptyRefineryInputs               = errors.New("empty refinery inputs")
	ErrUnexpectedExtractorInputs         = errors.New("unexpected extractor inputs")
	ErrDuplicateProductionInput          = errors.New("duplicate production input")
	ErrDuplicateProductionOutput         = errors.New("duplicate production output")
	ErrDuplicateBuildingInput            = errors.New("duplicate planet building input")
	ErrDuplicateBuildingOutput           = errors.New("duplicate planet building output")
	ErrEmptyBuildingOutput               = errors.New("empty planet building output")
	ErrInvalidProductionRate             = errors.New("invalid production rate per hour")
	ErrInvalidEnergyCost                 = errors.New("invalid energy cost per hour")
	ErrInvalidEnergyRate                 = errors.New("invalid planet energy rate")
	ErrInvalidStorageCapacity            = errors.New("invalid planet storage capacity")
	ErrStorageOverCapacity               = errors.New("planet storage over capacity")
	ErrDuplicateStorageItem              = errors.New("duplicate planet storage item")
	ErrUnknownStorageItem                = errors.New("unknown planet storage item")
	ErrZeroProductionTimestamp           = errors.New("zero planet production timestamp")
	ErrInvalidProductionState            = errors.New("invalid planet production state")
	ErrProductionSnapshotIncomplete      = errors.New("incomplete planet production snapshot")
	ErrInvalidProductionEvent            = errors.New("invalid planet production event")
	ErrInvalidProductionSettlementConfig = errors.New("invalid planet production settlement config")
	ErrInvalidRouteDestinationType       = errors.New("invalid route destination type")
	ErrInvalidRouteDestinationID         = errors.New("invalid route destination id")
	ErrInvalidRouteMapID                 = errors.New("invalid route map id")
	ErrInvalidRouteRisk                  = errors.New("invalid route risk")
	ErrInvalidRouteRate                  = errors.New("invalid route amount per hour")
	ErrInvalidRouteEnergyCost            = errors.New("invalid route energy cost per hour")
	ErrDuplicateRoute                    = errors.New("duplicate automation route")
	ErrRouteOwnerMismatch                = errors.New("route owner mismatch")
	ErrRouteSourceNotOwned               = errors.New("route source planet not owned")
	ErrRouteDestinationNotAccessible     = errors.New("route destination not accessible")
	ErrRouteResourceNotRouteable         = errors.New("route resource not routeable")
	ErrRouteRequirementNotMet            = errors.New("route requirement not met")
	ErrRouteCapacityExceeded             = errors.New("route capacity exceeded")
	ErrInvalidRouteDistance              = errors.New("invalid route distance")
	ErrRouteDistanceTooFar               = errors.New("route distance too far")
	ErrInvalidRouteCreateConfig          = errors.New("invalid route create config")
	ErrDuplicateBuilding                 = errors.New("duplicate planet building")
	ErrBuildingNotFound                  = errors.New("planet building not found")
	ErrInsufficientBuildingMaterials     = errors.New("insufficient planet building materials")
	ErrInvalidBuildingMutationCost       = errors.New("invalid planet building mutation cost")
	ErrInvalidBuildingMutationConfig     = errors.New("invalid planet building mutation config")
	ErrInvalidBuildingMutationReference  = errors.New("invalid planet building mutation reference")
	ErrStaleBuildingMutation             = errors.New("stale planet building mutation")
)

var (
	ErrInvalidAutomationRouteDurableCommit = errors.New("invalid automation route durable commit")
	ErrStaleAutomationRouteDurableCommit   = errors.New("stale automation route durable commit")
)

var (
	ErrInvalidRouteSettlementConfig   = errors.New("invalid route settlement config")
	ErrRouteNotFound                  = errors.New("automation route not found")
	ErrUnsupportedRouteDestination    = errors.New("unsupported route settlement destination")
	ErrRouteSourceStorageMissing      = errors.New("route source planet storage missing")
	ErrRouteDestinationStorageMissing = errors.New("route destination planet storage missing")
	ErrInvalidRouteLossRoll           = errors.New("invalid route loss roll")
	ErrInvalidRouteStorageLedger      = errors.New("invalid route storage ledger")
)

var ErrInvalidClaimProductionInitializerConfig = errors.New("invalid claim production initializer config")

var (
	ErrInvalidCraftLocationAuthorizerConfig = errors.New("invalid craft location authorizer config")
	ErrCraftPlanetNotOwned                  = errors.New("craft planet not owned")
	ErrCraftPlanetProductionMissing         = errors.New("craft planet production missing")
	ErrCraftBuildingNotFound                = errors.New("craft building not found")
	ErrCraftBuildingInactive                = errors.New("craft building inactive")
)
