package crafting

import "errors"

var (
	ErrDuplicateRecipeDefinition   = errors.New("duplicate recipe definition")
	ErrUnknownRecipeDefinition     = errors.New("unknown recipe definition")
	ErrRecipeSourceMismatch        = errors.New("recipe source definition mismatch")
	ErrInvalidRecipeCategory       = errors.New("invalid recipe category")
	ErrInvalidRecipeOutputKind     = errors.New("invalid recipe output kind")
	ErrEmptyRecipeInputs           = errors.New("empty recipe inputs")
	ErrDuplicateRecipeInput        = errors.New("duplicate recipe input")
	ErrInvalidRequiredRank         = errors.New("invalid required rank")
	ErrInvalidRequiredRole         = errors.New("invalid required role")
	ErrInvalidRequiredRoleLevel    = errors.New("invalid required role level")
	ErrDuplicateRoleRequirement    = errors.New("duplicate role requirement")
	ErrInvalidCraftLocationType    = errors.New("invalid craft location type")
	ErrEmptyCraftLocationID        = errors.New("empty craft location id")
	ErrLocationRequirementNotMet   = errors.New("location requirement not met")
	ErrRankRequirementNotMet       = errors.New("rank requirement not met")
	ErrRoleRequirementNotMet       = errors.New("role requirement not met")
	ErrInvalidCraftDuration        = errors.New("invalid craft duration")
	ErrEmptyCraftJobID             = errors.New("empty craft job id")
	ErrInvalidCraftJobState        = errors.New("invalid craft job state")
	ErrZeroCraftJobTime            = errors.New("zero craft job timestamp")
	ErrInvalidCraftJobTime         = errors.New("invalid craft job timestamp")
	ErrMissingRecipeCatalog        = errors.New("missing recipe catalog")
	ErrMissingItemDefinitions      = errors.New("missing item definition provider")
	ErrMissingReservationService   = errors.New("missing reservation service")
	ErrMissingInventoryService     = errors.New("missing inventory service")
	ErrMissingWalletService        = errors.New("missing wallet service")
	ErrMissingProgressionService   = errors.New("missing progression service")
	ErrMissingShipService          = errors.New("missing ship service")
	ErrMissingLocationAuthorizer   = errors.New("missing craft location authorizer")
	ErrUnknownCraftItem            = errors.New("unknown craft item definition")
	ErrCraftJobAlreadyExists       = errors.New("craft job already exists")
	ErrCraftStartReferenceMismatch = errors.New("craft start reference mismatch")
	ErrCraftJobNotFound            = errors.New("craft job not found")
	ErrCraftJobPlayerMismatch      = errors.New("craft job player mismatch")
	ErrCraftNotReady               = errors.New("craft job not ready")
	ErrCraftJobCancelled           = errors.New("craft job cancelled")
	ErrRecipeVersionMismatch       = errors.New("craft job recipe version mismatch")
	ErrUnsupportedRecipeOutput     = errors.New("unsupported recipe output")
	ErrCraftOutputAlreadyOwned     = errors.New("craft output already owned")
)
