package progression

import "errors"

var (
	ErrInvalidRoleType             = errors.New("invalid role type")
	ErrEmptySkillNodeID            = errors.New("empty skill node id")
	ErrInvalidLevel                = errors.New("invalid progression level")
	ErrInvalidRank                 = errors.New("invalid progression rank")
	ErrNegativeXP                  = errors.New("negative xp")
	ErrNegativeSkillPoints         = errors.New("negative skill points")
	ErrSpentSkillPointsExceedTotal = errors.New("spent skill points exceed total")
	ErrInvalidXPTable              = errors.New("invalid xp table")
	ErrDuplicateXPTableLevel       = errors.New("duplicate xp table level")
	ErrUnsortedXPTable             = errors.New("unsorted xp table")
	ErrLevelXPMismatch             = errors.New("level does not match xp table")
	ErrSnapshotPlayerMismatch      = errors.New("progression snapshot player mismatch")
	ErrDuplicateRoleLevel          = errors.New("duplicate role level")
	ErrDuplicateSkillNodeUnlock    = errors.New("duplicate skill node unlock")
	ErrUnknownSkillNode            = errors.New("unknown skill node")
	ErrInvalidSkillNodeDefinition  = errors.New("invalid skill node definition")
	ErrInvalidSkillBranch          = errors.New("invalid skill branch")
	ErrInvalidSkillPointCost       = errors.New("invalid skill point cost")
	ErrMissingSkillPrerequisite    = errors.New("missing skill prerequisite")
	ErrRankRequirementNotMet       = errors.New("rank requirement not met")
	ErrRoleRequirementNotMet       = errors.New("role requirement not met")
	ErrNotEnoughSkillPoints        = errors.New("not enough skill points")
	ErrInvalidXPSourceType         = errors.New("invalid xp source type")
	ErrEmptyXPSourceID             = errors.New("empty xp source id")
	ErrEmptyXPIdempotencyKey       = errors.New("empty xp idempotency key")
	ErrInvalidXPGrantAmount        = errors.New("invalid xp grant amount")
	ErrEmptyXPGrant                = errors.New("empty xp grant")
	ErrInvalidRankTarget           = errors.New("invalid rank target")
)
